workflow orchestrator added
TrataHQ/agentic-workflow pull request #4
Opened 2024-12-29 15:02 UTC by sheiksyedali

2024-12-29 15:37 UTC, hari-trata requested changes

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/adk/models/workflow.py
> +    # @field_validator('conditions', 'nextStepId')
why is this commented ?

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/api/routes/workflow.py
> +    return BaseResponse(message="Hello World", status="success")
pls remove test message like "Hello world"

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/api/routes/workflow.py
> +    await workflow_orchestrator.init_workflow_orchestrator(user.tenantModel.orgId, workflow_id)
dont understand why do we need to initialize workflow twice ?

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/workflow/models/workflow_context.py
> +#     data: Dict[str, Any] = Field(description="The data of the step")
Why are these commented ?

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +        placeholders = re.findall(r"\{(.*?)\}", value)
why is this regex required ? Can we have it without regex ?

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +async def nextStep(workflowContext: Dict[str, Any], workflowStep: WorkflowStep) -> str | None:
This is a clever way. Resolving next step through an action.

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/adk/models/workflow.py
> +    def to_dict(self):
why is to_dict required. There is something called model_dump which can convert these models to dict. Can we use that ?

2024-12-29 15:37 UTC, hari-trata commented on backend/agentic_workflow/api/routes/workflow.py
> +@router.post("/{workflow_id}/trigger", response_model=BaseResponse)
Is this a sync or async trigger ? If its async trigger, we have to return a run id so that people can check the status by asking the status of run id.

2024-12-30 15:01 UTC, sheiksyedali commented on backend/agentic_workflow/api/routes/workflow.py
> +@router.post("/{workflow_id}/trigger", response_model=BaseResponse)
async trigger. will implement properly in workflow APIs implementation

2024-12-30 15:16 UTC, hari-trata requested changes

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/models/workflow_context.py
> +    triggerPayload: Dict[str, Any] = Field(description="The payload of the trigger")
Just curious, do we need triggerPayload ? Can we use stepInput[triggerId] as the triggerPayload ?

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +with workflow.unsafe.imports_passed_through():
why is this required ?

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +        stepId: str | None = workflowCore.startStepId
nit: nextStepId

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    appPath = f"agentic_workflow.apps.{workflowStep.appId}.{workflowStep.appVersion}.definition" # TODO: We will get it from proer table
how does this work ? I think this will not work. We should use the same logic in sync_apps.

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    # TODO: Get credentials from corresponding table
why is this a todo ? pls fix it. Also we should refresh credentials if token is expired. Please check the api/connection.py.

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    executorName: str = stepPayload.name # TODO: Verify if this is the correct way to get the execution method (important player to get the execution method)
Why is this a TODO ? Isn't this the right way ?

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    action = next((a for a in actions if a.__class__.__name__ == executorName), None)
why do we get __class__.__name__. We already have action name for each action isn't it.

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +            conditionIndex = 0
why is this conditionIndex ? Just curious ?

2024-12-30 15:16 UTC, hari-trata commented on backend/agentic_workflow/api/routes/workflow.py
> +    await workflow_orchestrator.init_workflow_orchestrator(user.tenantModel.orgId, workflow_id, workflowCore, triggerPayload)
Why is this happen at trigger api ? We should have it in some common place during the service initialization like main.py

2024-12-30 15:16 UTC, hari-trata commented on backend/test-dsl.json
> +        "step1": {
Is this tested ? What is the obective of this dsl ?

2024-12-30 15:42 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +            conditionIndex = 0
This is being used. Not to address

2024-12-30 19:48 UTC, sheiksyedali commented on backend/agentic_workflow/api/routes/workflow.py
> +    await workflow_orchestrator.init_workflow_orchestrator(user.tenantModel.orgId, workflow_id, workflowCore, triggerPayload)
done

2024-12-30 19:48 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/models/workflow_context.py
> +    triggerPayload: Dict[str, Any] = Field(description="The payload of the trigger")
done

2024-12-30 19:49 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +        stepId: str | None = workflowCore.startStepId
done

2024-12-30 19:49 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    appPath = f"agentic_workflow.apps.{workflowStep.appId}.{workflowStep.appVersion}.definition" # TODO: We will get it from proer table
done

2024-12-30 20:04 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    executorName: str = stepPayload.name # TODO: Verify if this is the correct way to get the execution method (important player to get the execution method)
done

2024-12-30 20:04 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +    action = next((a for a in actions if a.__class__.__name__ == executorName), None)
done

2024-12-30 20:05 UTC, sheiksyedali commented on backend/test-dsl.json
> +        "step1": {
yes. testing purpose

2024-12-30 20:26 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +with workflow.unsafe.imports_passed_through():
To import non-temporal module.

Complications:
1. Performance: Temporal running in sandboxed environment. if we import non-temporal modules then each run it will be reloaded and may cause performance issue.

For our case we aware of our module execution so, we are good

2024-12-31 02:48 UTC, hari-trata approved these changes

2024-12-31 02:48 UTC, hari-trata commented on backend/agentic_workflow/api/routes/workflow.py
> +    await workflow_orchestrator.init_workflow_orchestrator(workflow_id, workflowCore, stepInputPayload, user)
Just curious, is this a sync or async call ? meaning does it wait for all the steps of workflow to execute completely ?

2024-12-31 02:48 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +with workflow.unsafe.imports_passed_through():
Thanks. this helps.

2024-12-31 02:48 UTC, hari-trata commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +                print(f"Error importing {module_name}: {e}")
is this equivalent to logging ? If not, can you please use logging instead of print ?

2024-12-31 05:57 UTC, sheiksyedali commented on backend/agentic_workflow/api/routes/workflow.py
> +    await workflow_orchestrator.init_workflow_orchestrator(workflow_id, workflowCore, stepInputPayload, user)
No, it is aync call. it doesn't wait for entire workflow execution

2024-12-31 06:14 UTC, sheiksyedali commented on backend/agentic_workflow/workflow/workflow_orchestrator.py
> +                print(f"Error importing {module_name}: {e}")
done. logging added

2024-12-31 06:23 UTC, merged